### PR TITLE
tests: add springboot pet-clinic

### PR DESCRIPTION
**Pull request by algomaster99**
The distribution of `pet-clinic` is not available on maven central. There exists [one ](https://mvnrepository.com/artifact/org.springframework.samples/spring-petclinic), but it is very old. As a workaround, I passed the executable jar as external jar.

We have some `NOT WHITELISTED` classes here:
```
[NOT WHITELISTED]: org/apache/logging/log4j/core/LoggerContext
[NOT WHITELISTED]: org/apache/logging/log4j/core/impl/Log4jProvider
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/NullConfiguration
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/ConfigurationStrSubstitutor
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/RuntimeStrSubstitutor
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/Interpolator
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/json/JsonConfigurationFactory
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/properties/PropertiesConfigurationFactory
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/xml/XmlConfigurationFactory
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/yaml/YamlConfigurationFactory
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ClassNamePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/DatePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/EncodingPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/EndOfBatchPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/EqualsReplacementConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/EqualsIgnoreCaseReplacementConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/FileLocationPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/FullLocationPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/HighlightConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LevelPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LineLocationPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LineSeparatorPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LoggerFqcnPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LoggerPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MapPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MarkerSimpleNamePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MarkerPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MaxLengthConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MdcPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MessagePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/MethodLocationPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/NanoTimePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/NdcPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/VariablesNotEmptyReplacementConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ProcessIdPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/RelativeTimePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/RepeatPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/RegexReplacementConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/SequenceNumberPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/StyleConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ThreadIdPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ThreadNamePatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/ThreadPriorityPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/UuidPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/AsyncAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/async/AsyncLoggerConfig
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/BurstFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/db/jdbc/FactoryMethodConnectionSource
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/ConsoleAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/ThreadContextMapFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/CountingNoOpAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/CronTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/CsvLogEventLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/CsvParameterLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/db/jdbc/DataSourceConnectionSource
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/DefaultRolloverStrategy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/action/DeleteAction
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/DenyAllFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/DirectWriteRolloverStrategy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/db/jdbc/DriverManagerConnectionSource
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/DynamicThresholdFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/FailoverAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/FileAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/CompositeFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/GelfLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/HtmlLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/HttpAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/routing/IdlePurgePolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/db/jdbc/JdbcAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/mom/jeromq/JeroMqAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/mom/JmsAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/JsonLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/mom/kafka/KafkaAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/net/ssl/KeyStoreConfiguration
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/LevelMatchFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/LevelRangeFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/MarkerFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/MemoryMappedFileAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/MessageLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/MutableThreadContextMapFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/NoMarkerFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/NoOpTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/nosql/NoSqlAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/NullAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/OnStartupTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/OutputStreamAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/PatternLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/CompositeTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/action/PosixViewAttributeAction
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/RandomAccessFileAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/RegexFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rewrite/RewriteAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/Rfc5424Layout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/RollingFileAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/RollingRandomAccessFileAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/routing/RoutingAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/script/Script
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/ScriptAppenderSelector
[NOT WHITELISTED]: org/apache/logging/log4j/core/script/ScriptFile
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/ScriptFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/script/ScriptRef
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/SerializedLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/SizeBasedTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/SmtpAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/SocketAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/StringMatchFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/StructuredDataFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/SyslogAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/SyslogLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/ThresholdFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/rolling/TimeBasedTriggeringPolicy
[NOT WHITELISTED]: org/apache/logging/log4j/core/filter/TimeFilter
[NOT WHITELISTED]: org/apache/logging/log4j/core/net/ssl/TrustStoreConfiguration
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/WriterAppender
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/XmlLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/layout/YamlLayout
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/IntegerPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/ResourceBundleLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/EnvironmentLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/EventLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/JavaLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/JndiLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/Log4jLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/MainMapLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/MarkerLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/lookup/SystemPropertiesLookup
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/HttpWatcher
[NOT WHITELISTED]: org/apache/logging/log4j/core/net/JndiManager
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/ConfigurationException
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/AppenderControl
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/AppenderLoggingException
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/ConfigurationScheduler
[NOT WHITELISTED]: org/apache/logging/log4j/core/util/WatchManager
[NOT WHITELISTED]: org/apache/logging/log4j/core/config/DefaultConfiguration
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/LiteralPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/SimpleLiteralPatternConverter
[NOT WHITELISTED]: org/apache/logging/log4j/core/pattern/DynamicWordAbbreviator
[NOT WHITELISTED]: org/apache/logging/log4j/core/util/StringBuilderWriter
[NOT WHITELISTED]: org/apache/logging/log4j/core/util/CloseShieldOutputStream
[NOT WHITELISTED]: org/apache/logging/log4j/core/appender/OutputStreamManager
[NOT WHITELISTED]: org/apache/logging/log4j/core/jmx/LoggerContextAdmin
[NOT WHITELISTED]: org/apache/logging/log4j/core/async/AsyncLoggerContext
[NOT WHITELISTED]: org/apache/logging/log4j/core/jmx/StatusLoggerAdmin
[NOT WHITELISTED]: org/springframework/samples/petclinic/owner/Owner
[NOT WHITELISTED]: org/springframework/samples/petclinic/model/Person
[NOT WHITELISTED]: org/springframework/samples/petclinic/vet/Vet
[NOT WHITELISTED]: org/springframework/samples/petclinic/model/NamedEntity
[NOT WHITELISTED]: org/springframework/samples/petclinic/owner/Pet
[NOT WHITELISTED]: org/springframework/samples/petclinic/owner/PetType
[NOT WHITELISTED]: org/springframework/samples/petclinic/owner/Visit
[NOT WHITELISTED]: org/springframework/samples/petclinic/vet/Specialty
```

### CODE REVIEW

**Comment by algomaster99** [comment]
I currently suspend thread for a minute to ensure that the springboot server started in the test, and then I destroy the process. This gives me a list of above classes that were reported as `NOT WHITELISTED`. @MartinWitt , any better idea how to test this?

**Comment by MartinWitt** [comment]
We could attach the agent and simulate some workload. To my knowledge, this spring application has some API. Also, the list of not whitelisted classes are no JDK classes, so this is good 🎉

**Comment by algomaster99** [comment]
>  Also, the list of not whitelisted classes are no JDK classes, so this is good

Yeah, this is nice :smile:

**Comment by algomaster99** [comment]
We will focus on level 4 later.

**Pull request closed without merging**
